package smartcampus.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import java.time.LocalDateTime;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.annotations.UpdateTimestamp;
import org.hibernate.type.SqlTypes;

/**
 * An interview question from the question bank (§38). Two populations live in one
 * table, separated by {@code ownerStudent}:
 *
 * <ul>
 *   <li>{@code ownerStudent IS NULL} — the GLOBAL bank, authored by an admin, readable
 *       by every authenticated user;
 *   <li>{@code ownerStudent = <id>} — a PRIVATE question, generated by the AI for
 *       exactly that student and visible to nobody else.
 * </ul>
 *
 * <p>Maps exactly to the {@code interview_questions} table created by
 * {@code V10__interview.sql}. {@code spring.jpa.hibernate.ddl-auto=validate} refuses to
 * boot on any drift between this mapping and that migration (PROJECT_PLAN.md
 * clarification G8).
 *
 * <p>An AI-generated question can never leak into the shared bank, and a curated one
 * can never be silently owned by a single student — both directions are CHECK-enforced
 * in the database.
 */
@Entity
@Table(name = "interview_questions")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
@EqualsAndHashCode(of = "id")
public class InterviewQuestion {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Enumerated(EnumType.STRING)
    @Column(name = "category", nullable = false, length = 20)
    private InterviewQuestionCategory category;

    @Enumerated(EnumType.STRING)
    @Column(name = "difficulty", nullable = false, length = 10)
    @Builder.Default
    private InterviewDifficulty difficulty = InterviewDifficulty.MEDIUM;

    @Column(name = "question", nullable = false, columnDefinition = "MEDIUMTEXT")
    @JdbcTypeCode(SqlTypes.LONGVARCHAR)
    private String question;

    @Column(name = "answer", nullable = true, columnDefinition = "MEDIUMTEXT")
    @JdbcTypeCode(SqlTypes.LONGVARCHAR)
    private String answer;

    @Column(name = "explanation", nullable = true, columnDefinition = "MEDIUMTEXT")
    @JdbcTypeCode(SqlTypes.LONGVARCHAR)
    private String explanation;

    @Column(name = "company_name", nullable = true, length = 150)
    private String companyName;

    @Column(name = "tags", nullable = true, length = 255)
    private String tags;

    @Enumerated(EnumType.STRING)
    @Column(name = "source", nullable = false, length = 20)
    @Builder.Default
    private InterviewQuestionSource source = InterviewQuestionSource.CURATED;

    @Column(name = "model", nullable = true, length = 120)
    private String model;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "owner_student_id", nullable = true)
    private Student ownerStudent;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "created_by", nullable = true)
    private User createdBy;

    @CreationTimestamp
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    @UpdateTimestamp
    @Column(name = "updated_at", nullable = false)
    private LocalDateTime updatedAt;
}
