-- V10__interview.sql  --  SmartCampus ERP interview-preparation schema (Phase 10, Interview)
--
-- Creates the three tables the interview module owns:
--   interview_questions          - the question bank (§38). Two populations live in one
--                                   table, separated by `owner_student_id`:
--                                     owner_student_id IS NULL  -> the GLOBAL bank,
--                                       authored by an admin, readable by every
--                                       authenticated user;
--                                     owner_student_id = <id>   -> a PRIVATE question,
--                                       generated by the AI for exactly that student and
--                                       visible to nobody else.
--                                   An AI-generated question can therefore never leak
--                                   into the shared bank, and a curated one can never be
--                                   silently owned by a single student - both directions
--                                   are CHECK-enforced below, not merely conventional.
--   interview_question_progress  - one row per (student, question): completion marking,
--                                   bookmark flag and the timestamp completion happened.
--                                   This is the whole of "completion marking, bookmarks
--                                   and progress tracking" in §38; the progress summary
--                                   endpoint aggregates this table and nothing else, so
--                                   no dashboard number in this module can be invented
--                                   (§60, §69).
--   interviews                   - scheduled interviews (§39) with a status lifecycle,
--                                   meeting link, and the CONFLICT-DETECTION guarantee
--                                   this phase is checkpointed on.
--
-- Creation order follows the FK dependency chain: interview_questions depends on
-- `students` and `users` (V2/V3), interview_question_progress on `students` and
-- interview_questions, interviews on `students` and `users`.
--
-- DELIBERATELY NO FOREIGN KEY INTO THE PLACEMENT (V8) OR RESUME (V9) SCHEMA. Phase 8 and
-- Phase 9 are being built in the same wave as this one and their table and column names
-- are not knowable here; an interview therefore records its company as plain
-- `company_name` text rather than referencing a `companies` row. Linking an interview to
-- a placement application is a later, additive migration if it is ever wanted - it is not
-- in §38/§39 scope.
--
-- Inherits utf8mb4 / utf8mb4_unicode_ci from the database default set in
-- V1__baseline.sql; each table still declares ENGINE/CHARSET/COLLATE explicitly, matching
-- V1-V7 style. utf8mb4 matters here for the same reason it does in V6: model-generated
-- question and answer text routinely contains non-BMP characters.

-- ---------------------------------------------------------------------------------------
-- interview_questions
-- ---------------------------------------------------------------------------------------
-- `question`, `answer` and `explanation` are MEDIUMTEXT, not TEXT: a worked answer to a
-- system-design or behavioural question clears the 65,535-byte TEXT ceiling easily, and a
-- truncated stored answer is a silent data-loss bug. The entity MUST map all three with
-- columnDefinition = "MEDIUMTEXT" AND @JdbcTypeCode(SqlTypes.LONGVARCHAR), exactly as
-- CodingProblem.description and AIMessage.content already do, or ddl-auto=validate
-- rejects the mapping at boot (clarification G8).
--
-- `model` is the id of the model that actually produced an AI-generated question. It is
-- the anti-fabrication anchor for this table, the counterpart of
-- chk_ai_messages_assistant_has_model in V6 and chk_coding_submissions_accepted_is_earned
-- in V7: a question labelled AI_GENERATED that no model produced cannot be written at
-- all. It is a model id, never a credential, and is safe to return to the owner.
--
-- `owner_student_id` cascades from `students` (which itself cascades from `users`): a
-- private question has no meaning without the student it was generated for. `created_by`
-- is ON DELETE SET NULL on purpose - removing the admin who authored a curated question
-- must not delete the question, and SET NULL (unlike RESTRICT) can never block the
-- users -> students -> interview_questions cascade above from completing.
CREATE TABLE interview_questions (
    id                BIGINT       NOT NULL AUTO_INCREMENT,
    category          VARCHAR(20)  NOT NULL,
    difficulty        VARCHAR(10)  NOT NULL DEFAULT 'MEDIUM',
    question          MEDIUMTEXT   NOT NULL,
    answer            MEDIUMTEXT   NULL,
    explanation       MEDIUMTEXT   NULL,
    company_name      VARCHAR(150) NULL,
    tags              VARCHAR(255) NULL,
    source            VARCHAR(20)  NOT NULL DEFAULT 'CURATED',
    model             VARCHAR(120) NULL,
    owner_student_id  BIGINT       NULL,
    created_by        BIGINT       NULL,
    created_at        DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT fk_interview_questions_owner_student
        FOREIGN KEY (owner_student_id) REFERENCES students (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_interview_questions_created_by
        FOREIGN KEY (created_by) REFERENCES users (id)
        ON DELETE SET NULL,
    -- The six §38 categories, exactly.
    CONSTRAINT chk_interview_questions_category
        CHECK (category IN ('TECHNICAL', 'HR', 'BEHAVIOURAL', 'CODING', 'APTITUDE',
                            'COMPANY_SPECIFIC')),
    CONSTRAINT chk_interview_questions_difficulty
        CHECK (difficulty IN ('EASY', 'MEDIUM', 'HARD')),
    CONSTRAINT chk_interview_questions_source
        CHECK (source IN ('CURATED', 'AI_GENERATED')),
    -- A blank question is an unanswerable row that would still be counted in every
    -- progress total. Enforced here as well as by @NotBlank so no path can write one.
    CONSTRAINT chk_interview_questions_question_not_blank
        CHECK (CHAR_LENGTH(TRIM(question)) > 0),
    -- §69, the anti-fabrication constraint: an AI_GENERATED row must name the model that
    -- produced it. A hand-written, cached or templated "AI question" has no model to
    -- name, so the database physically refuses to store it.
    CONSTRAINT chk_interview_questions_ai_has_model
        CHECK (source <> 'AI_GENERATED' OR model IS NOT NULL),
    -- Ownership and provenance are locked to each other in BOTH directions, so there is
    -- no state in which an AI-generated question is publicly visible, and none in which a
    -- curated bank question is privately owned:
    CONSTRAINT chk_interview_questions_ai_is_owned
        CHECK (source <> 'AI_GENERATED' OR owner_student_id IS NOT NULL),
    CONSTRAINT chk_interview_questions_curated_is_global
        CHECK (source <> 'CURATED' OR owner_student_id IS NULL),
    -- A COMPANY_SPECIFIC question with no company is uncategorisable and unfindable by
    -- the only filter that would ever surface it.
    CONSTRAINT chk_interview_questions_company_specific_has_company
        CHECK (category <> 'COMPANY_SPECIFIC' OR company_name IS NOT NULL)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

-- THE bank-browse query: the global bank narrowed by the two filters the UI exposes,
--   WHERE owner_student_id IS NULL AND category = ? AND difficulty = ?
-- with difficulty optional (a leftmost-prefix match on the first two columns).
CREATE INDEX idx_interview_questions_bank
    ON interview_questions (owner_student_id, category, difficulty);

-- "my AI-generated questions, newest first" - the private half of the same screen:
--   WHERE owner_student_id = ? ORDER BY created_at DESC
-- The FK above already indexes owner_student_id alone; this adds the ordering leg so the
-- sort is not a filesort.
CREATE INDEX idx_interview_questions_owner_created
    ON interview_questions (owner_student_id, created_at);

-- The company-specific filter ("show me Infosys questions"), which is a scan of the whole
-- bank without this index.
CREATE INDEX idx_interview_questions_company
    ON interview_questions (company_name);

-- ---------------------------------------------------------------------------------------
-- interview_question_progress
-- ---------------------------------------------------------------------------------------
-- One row per (student, question), created lazily the first time a student marks or
-- bookmarks that question. A student who has never touched a question has NO row here -
-- absence is the "not started" state, which is why the progress summary reports
-- notStarted as a derived difference rather than as a stored counter that could drift.
--
-- Keyed on `students`, not `users`: progress is an academic record, and every other
-- per-student artefact in this schema (enrollments, marks, ai_study_plans) is keyed the
-- same way. Both FKs cascade - progress about a deleted question, or belonging to a
-- deleted student, is meaningless.
CREATE TABLE interview_question_progress (
    id            BIGINT     NOT NULL AUTO_INCREMENT,
    student_id    BIGINT     NOT NULL,
    question_id   BIGINT     NOT NULL,
    completed     TINYINT(1) NOT NULL DEFAULT 0,
    bookmarked    TINYINT(1) NOT NULL DEFAULT 0,
    completed_at  DATETIME   NULL,
    created_at    DATETIME   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    DATETIME   NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    -- One progress row per student per question - the upsert target, and the reason a
    -- double-click on "mark complete" cannot create a second row that would double-count
    -- the student in every summary. Its leftmost column also serves every
    -- "this student's progress" lookup.
    UNIQUE KEY uk_interview_question_progress_student_question (student_id, question_id),
    CONSTRAINT fk_interview_question_progress_student
        FOREIGN KEY (student_id) REFERENCES students (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_interview_question_progress_question
        FOREIGN KEY (question_id) REFERENCES interview_questions (id)
        ON DELETE CASCADE,
    -- "Completed" and "there is no completion time" cannot both be true, and a completion
    -- time on an uncompleted row would make "completed this week" counts wrong. Un-marking
    -- a question MUST clear completed_at.
    CONSTRAINT chk_interview_question_progress_completed_at_consistent
        CHECK ((completed = 0 AND completed_at IS NULL)
               OR (completed = 1 AND completed_at IS NOT NULL))
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

-- The two list screens the student actually has: "my bookmarks" and "my completed
-- questions", both of which are WHERE student_id = ? AND <flag> = 1. The unique key above
-- carries student_id but not either flag.
CREATE INDEX idx_interview_question_progress_bookmarked
    ON interview_question_progress (student_id, bookmarked);

CREATE INDEX idx_interview_question_progress_completed
    ON interview_question_progress (student_id, completed);

-- ---------------------------------------------------------------------------------------
-- interviews
-- ---------------------------------------------------------------------------------------
-- A scheduled interview for one student (§39). The scheduling window is half-open:
-- [scheduled_start, scheduled_end). Two interviews OVERLAP when
--     a.scheduled_start < b.scheduled_end AND a.scheduled_end > b.scheduled_start
-- so back-to-back interviews (one ending exactly when the next begins) do NOT conflict.
--
-- CONFLICT DETECTION, and what this schema can and cannot do about it:
--
-- MySQL has no exclusion constraint, so general interval overlap CANNOT be expressed as a
-- table constraint - it is enforced in the service layer, inside one transaction, by a
-- SELECT ... FOR UPDATE over the student's active interviews before the insert (the gap
-- locks that range query takes are what stop two concurrent requests from both passing
-- the check).
--
-- What the schema CAN close is the narrowest and most likely race - two interviews for
-- the same student starting at the SAME instant - and it does, without breaking
-- rescheduling, via the generated column below. `active_slot_start` is scheduled_start
-- while the row is in a blocking status and NULL otherwise; because a UNIQUE index does
-- not compare NULLs, the key behaves as a PARTIAL unique index over active rows only. A
-- cancelled or completed interview therefore never blocks the slot it used to hold, while
-- two live ones can never share a start instant.
--
-- !! active_slot_start MUST NOT BE MAPPED ON THE JPA ENTITY. !!
-- It is computed by MySQL. Hibernate's ddl-auto=validate ignores database columns the
-- entity does not map, so leaving it unmapped is correct and safe; mapping it would make
-- every INSERT fail with "The value specified for generated column 'active_slot_start'
-- is not allowed".
--
-- `mode = 'ONLINE'` requires a meeting link: an online interview with no way to join it
-- is a §69 dead end on the student dashboard. `status = 'CANCELLED'` requires a reason,
-- so a cancellation is never unexplained. `outcome` may only exist on a COMPLETED
-- interview - recording a result for an interview that has not happened would be
-- fabricated data.
--
-- `created_by` is ON DELETE SET NULL for the same reason as in interview_questions: the
-- student's own user row can be the creator, and a RESTRICT here would block the
-- users -> students -> interviews cascade.
CREATE TABLE interviews (
    id                   BIGINT       NOT NULL AUTO_INCREMENT,
    student_id           BIGINT       NOT NULL,
    title                VARCHAR(200) NOT NULL,
    interview_type       VARCHAR(20)  NOT NULL,
    company_name         VARCHAR(150) NULL,
    round_name           VARCHAR(100) NULL,
    mode                 VARCHAR(10)  NOT NULL DEFAULT 'ONLINE',
    meeting_link         VARCHAR(500) NULL,
    location             VARCHAR(255) NULL,
    interviewer_name     VARCHAR(150) NULL,
    scheduled_start      DATETIME     NOT NULL,
    scheduled_end        DATETIME     NOT NULL,
    status               VARCHAR(20)  NOT NULL DEFAULT 'SCHEDULED',
    outcome              VARCHAR(20)  NULL,
    feedback             MEDIUMTEXT   NULL,
    notes                MEDIUMTEXT   NULL,
    cancellation_reason  VARCHAR(500) NULL,
    created_by           BIGINT       NULL,
    created_at           DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at           DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    -- Declared last, after every column it reads. Unmapped by JPA - see the note above.
    active_slot_start    DATETIME GENERATED ALWAYS AS (
                             CASE WHEN status IN ('SCHEDULED', 'RESCHEDULED')
                                  THEN scheduled_start END
                         ) STORED,
    PRIMARY KEY (id),
    -- The partial-unique slot key described above. A violation surfaces as a
    -- DataIntegrityViolationException and MUST be translated to the same 409 the
    -- service-layer overlap check produces - never allowed to reach the client as a 500.
    UNIQUE KEY uk_interviews_student_active_slot (student_id, active_slot_start),
    CONSTRAINT fk_interviews_student
        FOREIGN KEY (student_id) REFERENCES students (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_interviews_created_by
        FOREIGN KEY (created_by) REFERENCES users (id)
        ON DELETE SET NULL,
    CONSTRAINT chk_interviews_type
        CHECK (interview_type IN ('TECHNICAL', 'HR', 'BEHAVIOURAL', 'CODING', 'APTITUDE',
                                  'MANAGERIAL', 'MOCK')),
    CONSTRAINT chk_interviews_mode
        CHECK (mode IN ('ONLINE', 'ONSITE', 'PHONE')),
    CONSTRAINT chk_interviews_status
        CHECK (status IN ('SCHEDULED', 'RESCHEDULED', 'COMPLETED', 'CANCELLED', 'NO_SHOW')),
    CONSTRAINT chk_interviews_outcome
        CHECK (outcome IS NULL
               OR outcome IN ('AWAITING_RESULT', 'SELECTED', 'REJECTED', 'ON_HOLD')),
    CONSTRAINT chk_interviews_title_not_blank
        CHECK (CHAR_LENGTH(TRIM(title)) > 0),
    -- A zero-length or backwards window makes every overlap test meaningless, exactly as
    -- chk_coding_contests_window does for a contest.
    CONSTRAINT chk_interviews_window
        CHECK (scheduled_end > scheduled_start),
    CONSTRAINT chk_interviews_online_has_link
        CHECK (mode <> 'ONLINE' OR meeting_link IS NOT NULL),
    CONSTRAINT chk_interviews_cancelled_has_reason
        CHECK (status <> 'CANCELLED' OR cancellation_reason IS NOT NULL),
    CONSTRAINT chk_interviews_outcome_requires_completed
        CHECK (outcome IS NULL OR status = 'COMPLETED')
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

-- THE conflict-detection query, run before every schedule and every reschedule:
--   WHERE student_id = ?
--     AND status IN ('SCHEDULED', 'RESCHEDULED')
--     AND scheduled_start < :newEnd
--     AND scheduled_end   > :newStart
-- Leftmost student_id equality plus a range on scheduled_start; this is also the index
-- behind "this student's interviews, soonest first" and the dashboard's upcoming list.
CREATE INDEX idx_interviews_student_start
    ON interviews (student_id, scheduled_start);

-- The admin schedule board: "every upcoming interview" / "everything still SCHEDULED",
--   WHERE status = ? [AND scheduled_start BETWEEN ? AND ?] ORDER BY scheduled_start
-- which the student-scoped index above cannot serve (its leftmost column is student_id).
CREATE INDEX idx_interviews_status_start
    ON interviews (status, scheduled_start);
